### ISSUE TITLE
YAOCTRU_v7.0 doesn't work.

### ISSUE THREAD

**Issue by Qu1goN** [abbodi1406/WHD#3]
The Generator 6.0 and 7.0 make the .bat file but only the file from 6.0 works.

With the 7.0 comes the Error Findstr: cannot be opened and The system can not find the path specified etc. (see Screenshot)...?!

![Screen002](https://user-images.githubusercontent.com/62997079/92391794-8e2ed180-f11d-11ea-9d26-df32aa9a1909.jpg)

**Comment by abbodi1406** [comment]
Fixed, thanks
