### ISSUE TITLE
Converter script 79f.zip Missing Apps when creating ISO from Windows\SoftwareDistribution\Download

### ISSUE THREAD

**Issue by fgGitH2001** [abbodi1406/WHD#5]
Starting with latest Windows 11 Ni Builds (22H2), looks like MS Windows Update changed the way they download Apps in the SoftwareDistribution folder. 
If I use the latest current converter script 79f pointing to the folder C:\Windows\SoftwareDistribution\Download\96f67d863d4234d4823cdee8752abeee
it creates an ISO that is missing the Basic Windows Apps like SecHealthUI, MS Store and other Required Apps even if those are downloaded by W.U. in the folder.
Can the script be modified to include all the Windows Apps that are downloaded by Windows Update with the new Ni Builds?
In the past we could create a valid usable ISO simply directing the converter to the download folder 
C:\Windows\SoftwareDistribution\Download\96f67d863d4234d4823cdee8752abeee
but that does not work anymore unless we manually add a folder containing the Apps required for the specific Build.
Since W.U. is also downloading and updating the required Apps, it would be nice to have a converter script that creates a usable ISO that includes all the required Windows Apps without any other manual intervention, same as we used to do with all builds prior to the introduction of the Nickel builds (22H2).
Looking forward to a new converter script that can do all this automatically.
Thanks.

**Comment by abbodi1406** [comment]
It would be difficult to search and check all Apps folder in the source directory
not to mention that W.U. don't download all Apps, it only download new versions of the currently installed Apps.

so, the process is not always feasible, but i'll see what i can do

**Comment by abbodi1406** [comment]
Yes, it only download what's needed, which make it impossible to build ISO with all Apps based on W.U. upgrade folder
it's best to use Microsoft pre-built ISO, or download full UUP set from uupdump.net

**Comment by fgGitH2001** [comment]
Thank you.
Yes, that is what I've been doing. 
I was hoping to avoid multiple downloads like I used to do before these Nickel Builds. 🤷‍♂️

**Comment by abbodi1406** [comment]
You can download Apps files only from uupdump, just choose `Any Language' from the list

**Comment by fgGitH2001** [comment]
Already done it that way, thanks again.

**Comment by fgGitH2001** [comment]
Hello again, 
I downloaded the files and created the ISO for Build 25115.1000 and did a clean install of windows 11.
I was surprised to see that after the clean installwas done SecHealthUI was missing even if it was added to the Apps folder when the ISO was built. Why was SecHealthUI not installed during windows setup clean install?
Apparently to install an .appx file appinstaller is also required, but it is missing.
To work around the issue, I had to download the appinstaller from the MS Store and then I could install SecHealthUI simply clicking on the file from the Apps folder that was created during the process of building the ISO.

![image](https://user-images.githubusercontent.com/104878161/168402311-ed6d7b8a-f74a-40d2-811e-928a818707b2.png)

What needs to be done to avoid this problem?
Should AppInstaller be included in the Apps folder when the ISO is created?
Shouldn't AppInstaller be there after a clean install of Windows 11?
Thanks and regards, 
F.G.

**Comment by abbodi1406** [comment]
Investigating
can you share this log if still present?
`C:\Windows\Logs\DISM\DismAppx.log`

**Comment by fgGitH2001** [comment]
Here is the file I found.
I saw another thing looking at the level of Microsoft.DesktopAppInstaller it seems still an old version 1.17.10691.0_x64 instead of 1.18.692.0_x64.

[DismAppx.log](https://github.com/abbodi1406/WHD/files/8691971/DismAppx.log)

**Comment by abbodi1406** [comment]
We don't control the Apps version, it's whatever delivered with UUP files.

aside from the usual warnings, the integration process is successful

but as noted at MDL forums, build 25115 comes a changes to how apps are allowed, most of the apps are uninstalled after Windows is installed via AppReadiness service
`Get-AppxLog -All`
"Packages with the following full package names were not registered due to sideload policy restrictions:"

**Comment by fgGitH2001** [comment]
Thanks, 
I guess I'll have to wait for an official Dev MS ISO.

**Comment by fgGitH2001** [comment]
Hello again,
Looks like we have the same problem with Build 25120.
The Clean install with the Official MS insider ISO 25120 works fine and all the required apps are installed properly.
But when I use the ISO downloaded and created with the uup-dump script 79, many of the apps are removed after the installation and the system is basically unusable.
I don't understand how this ApprReadiness service work. ??

**Comment by fgGitH2001** [comment]
I used the same ISO created from uup-dump and did an update/repair in place on the same system that I did the clean install and after that all the apps where available including SecHealthUI. they all showed up in the Start Menu > All apps as new.

<img width="542" alt="image" src="https://user-images.githubusercontent.com/104878161/169243098-36cb0d1a-f03c-4665-8b84-71d23c8243ad.png">

**Comment by fgGitH2001** [comment]
OK, I'll give it a try. 
Probably tomorrow morning, it is 1:19AM here.
Thanks

**Comment by fgGitH2001** [comment]
Hello, 
I rebuild the ISO using uup-converter-wimlib-79r.7z as you suggested. pointing to the same uup folder that was created when I first downloaded 25120 from uup-dump.
I repeated the clean install with the new created ISO on the same machine that previously had the missing Apps and this time the Apps where present including SecHealthUI and all the other basic Windows Apps.
Thanks.

**Comment by fgGitH2001** [comment]
Hello again, 
Is it possible to get the version displayed with the letter suffix too, instead of just the basic version number?
This was with the latest download script for Build 25120.1010, it still shows 79, but since the clean installed worked fine without removing the Apps I assume it was actually done with 79r. Could you please clarify?
Thanks.
<img width="587" alt="image" src="https://user-images.githubusercontent.com/104878161/169715663-5c298e35-2b98-4a01-91c4-d40ba380aa9a.png">

**Comment by abbodi1406** [comment]
v80 will be released soon

**Comment by fgGitH2001** [comment]
Thank you.
