### ISSUE TITLE
PSFX Repack v6 doesn't work..!!

### ISSUE THREAD

**Issue by zerocoolroot** [abbodi1406/WHD#6]
Hi,

Firstly, sorry my bad english..!!

PSFX Repack v6 doesn't work to Windows10.0-KB5014019-x64.cab and Windows10.0-KB5014019-x64.psf.

![Print](https://user-images.githubusercontent.com/44586443/169618429-cea5b23d-b4ce-45c5-8b9f-ecdc98a8fdba.png)

Thanks in advance..!!

**Comment by abbodi1406** [comment]
Use psfx2esd_CLI.cmd to create ESD
or try PSFX MSU Maker

**Comment by zerocoolroot** [comment]
Hi,

I used **PSFX MSU Maker** and works fine..!!

![Screenshot_1](https://user-images.githubusercontent.com/44586443/169658274-3ab2a719-238f-40eb-bcab-807865f3f169.png)

But when I tryed to integrate to install.wim, I get this error..!!

![Screenshot_2](https://user-images.githubusercontent.com/44586443/169658537-79e5d40c-6a3e-4574-8d1b-9258482a4fba.png)

Firstly, I integrated SSU-22000.702-x64.cab.

**Comment by abbodi1406** [comment]
You have to add the msu file directly without extraction
MSMG Toolkit seems to use the old way "extract cab+psf" to add updates, that don't work with Win11 LCU msu
